# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

# GLOBALES FORMAT
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$java\
$gradle\
$kotlin\
$line_break\
$character"""

[character]
success_symbol = '[➜](bold green)'

[git_status]
disabled = false
untracked = ""

[package]
disabled = true

[java]
disabled = false
format = "via [$symbol($version )]($style) "  # ← Leerzeichen am Ende!
symbol = "☕ "
style = "red dimmed"
detect_extensions = ["java", "class", "jar", "gradle", "properties"]
detect_files = [
    "pom.xml",
    "build.gradle.kts",
    "build.sbt",
    ".java-version",
    "deps.edn",
    "project.clj",
    "build.boot",
    ".sdkmanrc"
]
detect_folders = ["src/main/java"]

[gradle]
disabled = false
format = "via [$symbol($version )]($style) "  # ← Leerzeichen am Ende!
symbol = "🅶  "
detect_extensions = ["gradle", "gradle.kts"]
detect_files = ["build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts"]
detect_folders = ["gradle"]

[kotlin]
disabled = false
format = "via [$symbol($version )]($style) "  # ← Leerzeichen am Ende!
symbol = "🅺  "
detect_extensions = ["kt", "kts"]
